user:
    name: Yessenia
    first_name: 来信
    last_name: 星夜
    email: admin@imalun.com
    domain: https://www.imalun.com
    avatar: https://c-ssl.duitang.com/uploads/blog/202210/20/20221020222629_d9c54.png
    describe: 网站简介。
    ruleText: 暂不接受个人博客以外的友链申请，确保您的网站内容积极向上，文章至少30篇，原创70%以上，部署HTTPS。

banner:
    index:
        type: video
        bgurl: img/未定事件簿-莫弈-迷弭惊鸟-2.mp4
        bannerTitle: ，<br>pu'xing。
        bannerText: Hi my new friend!

favicon:
    logo: logo.svg
    icon16: logo.svg
    icon32: logo.svg
    appleTouchIcon: apple-touch-icon.png
    webmanifest: /site.webmanifest
    visibilitychange: true
    hidden: failure.ico
    showText: 
    hideText: (●—●)等你回来哦

assets:
    internal_provider: unpkg # local（不使用） | unpkg | jsdelivr
    third_party_provider: https://npm.elemecdn.com # unpkg | jsdelivr #可以使用第三方
    

top_bars:
    - title: 首页
      url: /
      children:
          - title: archives2
            url: /archives2/
    - title: 归档
      url: /archives/
    - title: 分类
      url: /categories/
    - title: 标签
      url: /tags/
sidebar:
    typedTextPrefix: A
    typedText: ["little space of my"]
    social: # 社交地址
        - name: github
          icon: fab fa-github
          url: https://github.com
        - name: gitee
          icon: iconfont cg-gitee
          url: https://gitee.com
        - name: lofter
          icon: fas fa-snowboarding
          url: https://xingyelaixin.lofter.com/


toc:
    enable: true
    list_number: true
    max_depth: 3
    min_depth: 1


layout:
    path: layout

footer:
  powered:
    enable: true
  beian:
    enable: false
    icp: 
  copyrightYear: 2023
  live_time:
    enable: true
    prefix: footer.tips
    start_time: 08/07/2023 17:00:00
  custom_text:

    