user:
    name: 白云苍狗
    first_name: 苍狗
    last_name: 白云
    email: admin@imalun.com
    domain: https://www.imalun.com
    avatar: /img/avatar.jpg
    describe: 网站简介。
    ruleText: 暂不接受个人博客以外的友链申请，确保您的网站内容积极向上，文章至少30篇，原创70%以上，部署HTTPS。
    
favicon:
    logo: logo.svg
    icon16: logo.svg
    icon32: logo.svg
    appleTouchIcon: apple-touch-icon.png
    webmanifest: /site.webmanifest
    visibilitychange: true
    hidden: failure.ico
    showText: 
    hideText: (●—●)等你回来哦

assets:
    internal_provider: unpkg # local（不使用） | unpkg | jsdelivr
    third_party_provider: https://npm.elemecdn.com # unpkg | jsdelivr #可以使用第三方

sidebar:
    typedTextPrefix: A
    typedText: ["little space of me"]
    social: # 社交地址
        - name: github
          icon: fab fa-github
          url: https://github.com
        - name: gitee
          icon: iconfont cg-gitee
          url: https://gitee.com
        - name: lofter
          icon: fas fa-snowboarding
          url: https://xingyelaixin.lofter.com/

