sw: true #PWA
user:
    name: Yessenia
    first_name: 来信
    last_name: 星夜
    email: admin@imalun.com
    domain: https://www.imalun.com
    avatar: https://pic1.zhimg.com/80/v2-b40c6aeeced6da9931ce74640452425c_720w.webp
    describe: 网站简介。
    ruleText: 暂不接受个人博客以外的友链申请，确保您的网站内容积极向上，文章至少30篇，原创70%以上，部署HTTPS。

banner:
    index:
        type: video
        bgurl:  https://cdn.jsdelivr.net/gh/YesseniaCQ/img/video/迷弭惊鸟-2/迷弭惊鸟-2.m3u8
        bannerTitle: 欢迎来到，<br>铺星小筑。
        bannerText: Hi my new friend!
    archive:
        type: video
        bgurl: https://cdn-51a5.allflow.com.cn/oss/51fe18b9-b347-477f-97dd-96558c1c790f/%25E6%259C%25AA%25E5%25AE%259A%25E4%25BA%258B%25E4%25BB%25B6%25E7%25B0%25BF-%25E8%258E%25AB%25E5%25BC%2588-%25E8%25BF%25B7%25E5%25BC%25AD%25E6%2583%258A%25E9%25B8%259F-2.mp4?filename=%E6%9C%AA%E5%AE%9A%E4%BA%8B%E4%BB%B6%E7%B0%BF-%E8%8E%AB%E5%BC%88-%E8%BF%B7%E5%BC%AD%E6%83%8A%E9%B8%9F-2.mp4&time=1691579700&token=dc73322894486fba94e5415fd878af4b&role=share
        bannerTitle: 线与时光，<br>组成我。
    about:
        type: img
        bgurl: https://cdn.jsdelivr.net/gh/YesseniaCQ/img/未定事件簿-莫弈-浮香黯光-1.mp4
        bannerTitle: 学习之外，<br>净土之上。
favicon:
    logo: logo.svg
    icon16: logo.svg
    icon32: logo.svg
    appleTouchIcon: apple-touch-icon.png
    webmanifest: /site.webmanifest
    visibilitychange: true
    hidden: failure.ico
    showText: ""
    hideText: (●—●)等你回来哦

assets:
    internal_provider: unpkg # local（不使用） | unpkg | jsdelivr
    third_party_provider: https://npm.elemecdn.com # unpkg | jsdelivr #可以使用第三方
    

top_bars:
    - title: 首页
      url: /
      children:
          - title: archives2
            url: /archives2/
    - title: 归档
      url: /archives/
    - title: 分类
      url: /categories/
    - title: 标签
      url: /tags/
    - title: 关于我
      url: /about/
sidebar:
    typedTextPrefix: A
    typedText: ["little space of my"]
    social: # 社交地址
        - name: github
          icon: fab fa-github
          url: https://github.com
        - name: gitee
          icon: iconfont cg-gitee
          url: https://gitee.com
        - name: lofter
          icon: fas fa-snowboarding
          url: https://xingyelaixin.lofter.com/
    info: # 个人信息
        - key: 地址
          val: 铺星小筑
        - key: 年龄
          val: 21


toc:
    enable: true
    list_number: true
    max_depth: 3
    min_depth: 1


layout:
    path: layout
    tag: async/tag

footer:
  powered:
    enable: true
  beian:
    enable: false
    icp: 
  copyrightYear: 2023
  live_time:
    enable: true
    prefix: footer.tips
    start_time: 08/07/2023 17:00:00
  custom_text:

categorie_card:
    enable: true
    len: 2
    list: ["生信", "分类2"]

#右下角悬浮按钮块
rightside:
    readmode: true
    aside: true

datetime_foramt:
    post_card:
        date: YY/MM/DD
        time: HH:mm
    post_info:
        date: MM/DD
        time: HH:mm
    archive:
        date: MM/DD
        time: HH:mm

highlight:
    theme: true
    title: default
    copy: true
    lang: true
    code_word_wrap: fasle
    height_limit: 200 # 超出时，显示折叠按钮

wordcount:
    enable: true
    count: true
    time: true

webAnalytics:  
  enable: true
  baidu:  百度统计Key

search:
  enable: true
  type: local
  preload: true
  trigger: auto

  katex:
  copy_tex: true
  global: true
  options: {}

videoPlayerResourcesUrl:
     - https://unpkg.com/video.js@6.7.1/dist/video-js.css
     - https://unpkg.com/video.js@6.7.1/dist/video.js
     - https://unpkg.com/@videojs/http-streaming@0.9.0/dist/videojs-http-streaming.js